CREATE TABLE warehouse.birth_country_mapping (
	raw_birth_country varchar(250),
	country_code char(2)
);

INSERT INTO warehouse.birth_country_mapping (
	raw_birth_country,
	country_code
)
VALUES
('17e Arrondissement France', 'FR'),
('Afghanistan', 'AF'),
('Algérie', 'DZ'),
('Argentina', 'AR'),
('Armenia', 'AM'),
('Australia', 'AU'),
('Australie', 'AU'),
('Austria', 'AT'),
('Austria-Hungary now Austria', 'AT'),
('Austria-Hungary now Hungary', 'HU'),
('Austria-Hungary now Poland', 'PL'),
('Austria-Hungary now Romania', 'RO'),
('Austria-Hungary now Serbia', 'RS'),
('Austria-Hungary now Ukraine', 'UA'),
('Austro-Hungarian Empire now Ukraine', 'UA'),
('Autriche', 'AT'),
('Barbados', 'BB'),
('Belgio', 'BE'),
('Belgium', 'BE'),
('Bhutan', 'BT'),
('Bismarck - North Dakota - USA', 'US'),
('Bohemia', 'CZ'),
('Bosnia and Herzegovina', 'BA'),
('Brazil', 'BR'),
('British Guiana now Guyana', 'GY'),
('British India', 'IN'),
('British Palestine', 'PS'),
('Budapest', 'HU'),
('Buenos Aires - Argentina', 'AR'),
('Bulgaria', 'BG'),
('California', 'US'),
('Cambodia', 'KH'),
('Canada', 'CA'),
('Central Vietnam', 'VN'),
('Československo', 'CZ'),
('Chelsea - Massachusetts - USA', 'US'),
('Chile', 'CL'),
('China', 'CN'),
('Colombia', 'CO'),
('Copenhagen - Denmark', 'DK'),
('Croatia', 'HR'),
('Crook - Durham - England - UK', 'GB'),
('CT', 'US'),
('Cuba', 'CU'),
('Cyprus', 'CY'),
('Czech Republic', 'CZ'),
('Czechia', 'CZ'),
('Czechoslovakia', 'CZ'),
('Czechoslovakia now Czech Republic', 'CZ'),
('Czechoslovakia now Slovak Republic', 'SK'),
('Dahomey now Benin', 'BJ'),
('Danimarca', 'DK'),
('Danmark', 'DK'),
('Denmark', 'DK'),
('East Germany now Germany', 'DE'),
('Egypt', 'EG'),
('England', 'GB'),
('England UK', 'GB'),
('Eritrea', 'ER'),
('España', 'ES'),
('Estados Unidos', 'US'),
('États-Unis', 'US'),
('Ethiopia', 'ET'),
('Finland', 'FI'),
('Flint - Michigan - USA', 'US'),
('France', 'FR'),
('Francia', 'FR'),
('Frauenfeld - Switzerland', 'CH'),
('French Algeria now Algeria', 'DZ'),
('French Polynesia', 'PF'),
('French Protectorate of Tunisia now Tunisia', 'TN'),
('Georgia', 'US'),
('German Democratic Republic now Germany', 'DE'),
('German Reich now Poland', 'PL'),
('German Reich now Russia', 'RU'),
('Germania', 'DE'),
('Germany', 'DE'),
('Giappone', 'JP'),
('Grecia', 'GR'),
('Greece', 'GR'),
('Gunderup v/ Aalborg', 'DK'),
('Guyana', 'GY'),
('Haiti', 'HT'),
('Haute-Savoie - France', 'FR'),
('Hong Kong', 'HK'),
('Hungarian People''s Republic now Hungary', 'HU'),
('Hungary', 'HU'),
('Iceland', 'IS'),
('Illinois', 'US'),
('India', 'IN'),
('Indiana', 'US'),
('Iran', 'IR'),
('Ireland', 'IE'),
('Irlanda', 'IE'),
('Israel', 'IL'),
('Italia', 'IT'),
('italy', 'IT'),
('Italy', 'IT'),
('Jamaica', 'JM'),
('Japan', 'JP'),
('Keene - New Hampshire - USA', 'US'),
('Kenya', 'KE'),
('Korea', 'KR'),
('Laos', 'LA'),
('Latvia', 'LV'),
('Lebanon', 'LB'),
('Lithuania', 'LT'),
('London', 'GB'),
('Lussemburgo', 'LU'),
('Macedonia now North Macedonia', 'MK'),
('Malaysia', 'MY'),
('Mali', 'ML'),
('Mandatory Palestine now Israel', 'IL'),
('Mauritania', 'MR'),
('Mérida - Yucatán - Mexico', 'MX'),
('Mexico', 'MX'),
('México', 'MX'),
('Mexico City - Distrito Federal - Mexico', 'MX'),
('Michigan USA', 'US'),
('Minnesota', 'US'),
('Mississippi', 'US'),
('Missouri', 'US'),
('Moğolistan', 'MN'),
('Monaco', 'MC'),
('Montenegro', 'ME'),
('Morocco', 'MA'),
('Myślenice', 'PL'),
('Netherlands', 'NL'),
('New Jersey', 'US'),
('New York', 'US'),
('New York City', 'US'),
('New Zealand', 'NZ'),
('Nigeria', 'NG'),
('Northern Ireland', 'GB'),
('Norway', 'NO'),
('Nuova Zelanda', 'NZ'),
('NY', 'US'),
('Ohio', 'US'),
('Omaha - Nebraska - USA', 'US'),
('Ontario', 'CA'),
('Oregon USA', 'US'),
('PA', 'US'),
('Pakistan', 'PK'),
('Palestine', 'PS'),
('Palestine now Israel', 'IL'),
('Paris - France', 'FR'),
('Passaic - New Jersey - USA', 'US'),
('Peru', 'PE'),
('Philippines', 'PH'),
('Poland', 'PL'),
('Polish People''s Republic now Poland', 'PL'),
('Polska', 'PL'),
('Polska obecnie Ukraina', 'UA'),
('Portugal', 'PT'),
('Protektorát Čechy a Morava now Czech Republic', 'CZ'),
('Puerto Rico', 'PR'),
('Regno Unito', 'GB'),
('Republic of Georgia', 'GE'),
('Republic of Ireland', 'IE'),
('Riverside - California - USA', 'US'),
('Roma', 'IT'),
('Romania', 'RO'),
('Romania now Moldova', 'MD'),
('Romanian SR now Romania', 'RO'),
('Roumanie', 'RO'),
('Rusia', 'RU'),
('Russia', 'RU'),
('Russia Empire', 'RU'),
('Russian Empire', 'RU'),
('Russian Empire now Belarus', 'BY'),
('Russian Empire now Poland', 'PL'),
('Russian Empire now Russia', 'RU'),
('Russian Empire now Ukraine', 'UA'),
('San Giorgio a Cremano', 'IT'),
('Sandy - Oregon - USA', 'US'),
('Scotland', 'GB'),
('Serbia', 'RS'),
('Singapore', 'SG'),
('Slovenia', 'SI'),
('Somalia', 'SO'),
('Sondrio', 'IT'),
('Sosnovka Berezovsky district of the Perm region', 'RU'),
('South Africa', 'ZA'),
('South African Republic', 'ZA'),
('South Korea', 'KR'),
('Spagna', 'ES'),
('Spain', 'ES'),
('Stati Uniti', 'US'),
('Sverige', 'SE'),
('Svezia', 'SE'),
('Swaziland now Eswatini', 'SZ'),
('Sweden', 'SE'),
('Switzerland', 'CH'),
('Syria', 'SY'),
('Taiwan', 'TW'),
('Tasmania', 'AU'),
('Tennessee', 'US'),
('Texas', 'US'),
('Thailand', 'TH'),
('the Netherlands', 'NL'),
('The Netherlands', 'NL'),
('Tunisia', 'TN'),
('Turchia', 'TR'),
('Turkey', 'TR'),
('Uganda', 'UG'),
('UK', 'GB'),
('Ukraina', 'UA'),
('Ukraine', 'UA'),
('Ukrainian SSR', 'UA'),
('United Arab Republic now Egypt', 'EG'),
('United Kingdom', 'GB'),
('United States', 'US'),
('United States of America', 'US'),
('Uruguay', 'UY'),
('US', 'US'),
('US Virgin Islands', 'VI'),
('USA', 'US'),
('USSR', 'RU'),
('USSR now Estonia', 'EE'),
('USSR now Russia', 'RU'),
('USSR now Tajikistan', 'TJ'),
('USSR Russia', 'RU'),
('Uxbridge - Hillingdon - Middlesex - England - UK', 'GB'),
('Venezuela', 'VE'),
('Vermont', 'US'),
('Vienna - Austria', 'AT'),
('Vietnam', 'VN'),
('Vietnam now Ho Chi Minh City', 'VN'),
('Wales', 'GB'),
('Washington', 'US'),
('Weimar Republic now Germany', 'DE'),
('West Bank', 'PS'),
('West Germany now Germany', 'DE'),
('Wisconsin', 'US'),
('Yugoslavia', 'YU'),
('Yugoslavia now North Macedonia', 'MK'),
('Yugoslavia now Serbia', 'RS'),
('Yugoslavia now Serbia and Montenegro', 'CS'),
('Zambia', 'ZM'),
('Zvenigorod', 'RU'),
('Германия', 'DE'),
('Россия', 'RU'),
('США', 'US');